### ISSUE TITLE
Metaはどのように使いますか？

### ISSUE THREAD

**Issue by ikedaisuke** [ikedaisuke/OnlineStudyMeetings#2]
Metaの使い道がいまいちわからないのですが…

**Comment by IKEGAMIDaisuke** [comment]
Metaはこの勉強会システムそのものについての議論に使ってみてはいかがでしょうか。たとえばルートディレクトリに置くのは躊躇するけれど、何か置きたいとか。単にIssueで語り合うだけではとどまらないものを置きたい場合を想定しています。各勉強会と別に隔離したかっただけなので、必要がないかも知れません。
